# Generated by Django 5.2.3 on 2025-06-19 03:53

import catalog.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('published_date', models.DateField()),
                ('isbn', models.CharField(max_length=13, unique=True)),
                ('page_count', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('language', models.CharField(blank=True, max_length=50, null=True)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to=catalog.models.cover_upload_path)),
            ],
        ),
    ]
